---
- include: env.yml
- include: versions.yml

- name: "Remove symbolic links to tools which have state absent"
  file:
    path: "{{ hashicorp_bin_dir }}/{{ item.key }}{{ hashicorp_tool_suffix }}"
    state: "absent"
  become: yes
  when: item.value.action == "remove" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"

- name: Ensure HashiCorp tools with state absent is remove
  file:
    dest: "{{ hashicorp_install_dir }}/hashicorp-{{item.key}}/{{item.value.installed_version}}"
    state: absent
  become: yes
  when: item.value.action == "remove" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"

- name: Downloads tools
  get_url:
    url: "{{ hashicorp_releases_location }}/{{item.key}}/{{item.value.version}}/{{item.key}}_{{item.value.version}}_{{hashicorp_architecture}}.zip"
    dest: "{{ hashicorp_tmp_dir }}"
    mode: 0755
    validate_certs: no
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"
  changed_when: False

- name: Download tool checksum files
  get_url:
    url: "{{ hashicorp_releases_location }}/{{item.key}}/{{item.value.version}}/{{item.key}}_{{item.value.version}}_SHA256SUMS"
    dest: "{{ hashicorp_tmp_dir }}"
    mode: 0755
    validate_certs: no
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"
  changed_when: False

- name: Verify downloaded files
  shell: cat "{{item.key}}_{{item.value.version}}_SHA256SUMS" | grep "{{hashicorp_architecture}}" | sha256sum -c -
  args:
    chdir: "{{ hashicorp_tmp_dir }}"
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"
  register: cmd_sha256sum
  changed_when: False
  failed_when: cmd_sha256sum.rc|default(1) == 1

- name: Ensure HashiCorp tool directory exists
  file:
    path: "{{ hashicorp_install_dir }}/hashicorp-{{item.key}}/{{item.value.version}}/bin"
    state: directory
    mode: 0755
  become: yes
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"

- name: Unpack download packages
  unarchive:
    src: "{{ hashicorp_tmp_dir }}/{{item.key}}_{{item.value.version}}_{{hashicorp_architecture}}.zip"
    dest: "{{ hashicorp_install_dir }}/hashicorp-{{item.key}}/{{item.value.version}}/bin"
    copy: no
    mode: 0755
    owner: "{{ hashicorp_system_user }}"
    group: "{{ hashicorp_system_group }}"
    creates: "{{ hashicorp_install_dir }}/hashicorp-{{item.key}}/{{item.value.version}}/bin/{{item.key}}"
  become: yes
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"

- name: Creates symbolic links to Hashicorp tools
  file:
    src: "{{ hashicorp_install_dir }}/hashicorp-{{item.key}}/{{item.value.version}}/bin/{{item.key}}"
    dest: "{{ hashicorp_bin_dir }}/{{item.key}}{{ hashicorp_tool_suffix }}"
    state: link
  become: yes
  when: item.value.action == "install" or item.value.action == "replace"
  with_dict: "{{hashicorp_tools_work}}"

- include: consul/main.yml
  when: (hashicorp_tools_work.consul.state|default("")) != "" and (hashicorp_tools_work.consul.state|default("")) != "absent"

- include: cleanup.yml

