---
# handlers file

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  when: hashicorp_consul_service_enabled|bool == true

- name: restart consul
  service:
    name: consul
    state: restarted
  become: true
  when: hashicorp_consul_service_enabled|bool == true

- name: reload consul
  service:
    name: consul
    state: reloaded
  become: true
  when: hashicorp_consul_service_enabled|bool == true
  